### ISSUE TITLE
[BUG] Can't close the window about plugin

### ISSUE THREAD

**Issue by YIRU69** [denisoed/obsidian-orthography#17]
Hi, thanks for you make the plugin.
I have a probrom when I use it.
![2](https://user-images.githubusercontent.com/48148292/160058649-0b9f7065-e303-4c43-8d1a-3ae141dcdfe6.gif)
I can't close the window about plugin.
What's wrong with it?

**Comment by YIRU69** [comment]
Hi ,look at the picture.
![image](https://user-images.githubusercontent.com/48148292/160058929-238a1590-abe5-4066-85cf-b0fa077bdebb.png)

**Comment by denisoed** [comment]
@YIRU69 Hi

The plugin does not work correctly in the "Live Preview" mode :(
I'll figure it out and fix it

**Comment by YIRU69** [comment]
@VidathD Hi, friend, this is another error that I said.
![1](https://user-images.githubusercontent.com/48148292/160059380-1b4fcf2a-8b62-4e9c-8abf-85a7df45c9c7.gif)
Step:
1. start to load plugin
2. check the button `Run orthography check` in the source mode
3. and then the error like the gif.

**Comment by YIRU69** [comment]
```
Uncaught TypeError: Cannot read properties of undefined (reading 'getAllMarks')
    at onPopupClose (eval at <anonymous> (app.js:1:1433712), <anonymous>:790:35)
    at e.tryTrigger (app.js:1:838297)
    at e.trigger (app.js:1:838230)
    at OrthographyToggler.setButtonWithRunner (eval at <anonymous> (app.js:1:1433712), <anonymous>:526:24)
    at HTMLButtonElement.toggle (eval at <anonymous> (app.js:1:1433712), <anonymous>:482:20)
onPopupClose @ main.ts:147
e.tryTrigger @ app.js:1
e.trigger @ app.js:1
setButtonWithRunner @ orthographyToggler.ts:107
toggle @ orthographyToggler.ts:56
setTimeout (async)
e.tryTrigger @ app.js:1
e.trigger @ app.js:1
setButtonWithRunner @ orthographyToggler.ts:107
toggle @ orthographyToggler.ts:56

```

**Comment by YIRU69** [comment]
Hope you can quickly to fix it. I love you plugin very much.

**Comment by denisoed** [comment]
@YIRU69  Please, try changing the mode to "Source mode"

![image](https://user-images.githubusercontent.com/17797700/160059866-a70a9c51-1f8c-46ae-a877-698c5b713d41.png)

**Comment by YIRU69** [comment]
> @YIRU69 Please, try changing the mode to "Source mode"
> 
> ![image](https://user-images.githubusercontent.com/17797700/160059866-a70a9c51-1f8c-46ae-a877-698c5b713d41.png)

I am actually on the Source mode!

**Comment by denisoed** [comment]
@YIRU69  I will fix this bug. Thanks

**Comment by YIRU69** [comment]
```
Uncaught TypeError: this.activeEditor.off is not a function
    at HTMLDocument.eval (eval at <anonymous> (app.js:1:1433712), <anonymous>:693:35)
```

**Comment by voidtriangle** [comment]
Workaround to close the window.

1. Navigate: <Your_obsidian_vault> \\.obsidian\plugins\obsidian-orthography
2. Find file name "main.js"
3. **Comment Line** or **Remove** following lines onPopupClose () function  

      if (self.activeEditor)
            self.activeEditor.doc.getAllMarks().forEach((m) => m.clear());

![commet](https://user-images.githubusercontent.com/107706537/174340265-5c97bdb7-e44b-4cb9-901a-61bd09b042f5.jpg)

**Comment by YIRU69** [comment]
@voidtriangle Thanks for you advise. I will test it.

**Comment by denisoed** [comment]
Fixed
