### ISSUE TITLE
Unable to "correct a word mistake in one click," nor close the checking window

### ISSUE THREAD

**Issue by sammo3182** [denisoed/obsidian-orthography#19]
Denis, first of all, thank you so very much for the plugin. Grammarly not integrated into Obsidian is really a pain in the ass! Your work gives me hope of solving it. I work on Win 11 and the source mode as you suggest. The plugin works well for identifying the errors in the separate window, but when I click it, nothing changes in the text while the error disappears in the separate window. So, basically, no "Correct a word mistake in one click." I also have the problem mentioned in #17. 

As one who also develops software, I know it takes time to fix bugs, especially for an open-source piece. So I would like to appreciate the attention and all the efforts to fix these problems ahead! Thank you again for contributing to integrating Grammarly into obsidian!

**Comment by denisoed** [comment]
Fixed
