### ISSUE TITLE
Request to Implement Personal Dictionary

### ISSUE THREAD

**Issue by KarolinaMaczka** [denisoed/obsidian-orthography#23]
Hello,
I really like this project! I saw the "personal dictionary" listed in the TODO section of the README and would love to contribute by implementing it. Could I have your permission to start working on this feature?

**Comment by denisoed** [comment]
Hello 👋 

Yes, of course, you can add new functionality. And thanks for the feedback ☺️

**Comment by KarolinaMaczka** [comment]
Great, thank you.
Let me know whether you like the design. Anything you'd like to change, please write.
![image](https://github.com/user-attachments/assets/3d3f2687-e540-4efc-874d-08685e682ddf)
![image](https://github.com/user-attachments/assets/770e76dc-6652-4a62-bfc0-63c00560c079)

**Comment by denisoed** [comment]
@KarolinaMaczka I would adjust the colors and padding for all elements. Maybe I can make changes to your git branch?

**Comment by KarolinaMaczka** [comment]
Yes, sure, you can: https://github.com/KarolinaMaczka/obsidian-orthography/tree/personal-dictionary

**Comment by denisoed** [comment]
@KarolinaMaczka I've started working on improving the styles. I will push changes to your git branch

**Comment by denisoed** [comment]
@KarolinaMaczka I've made the changes to your [git branch](https://github.com/KarolinaMaczka/obsidian-orthography/tree/personal-dictionary), you can check it out and if all is well then create a merge request.

**Comment by KarolinaMaczka** [comment]
ok, I've checked it and created a merge request, I added one small commit, explained in the request comment.

**Comment by denisoed** [comment]
@KarolinaMaczka Thank you for your contribution to the project :)

https://github.com/denisoed/obsidian-orthography/releases/tag/3.1.0

**Comment by denisoed** [comment]
https://github.com/denisoed/obsidian-orthography/releases/tag/3.1.0
