### ISSUE TITLE
WIP:Add integration to Grammarly

### ISSUE THREAD

**Issue by ddark008** [denisoed/obsidian-orthography#5]
Variants:
Unofficial Grammarly API Client
https://github.com/stewartmcgown/grammarly-api

**Comment by denisoed** [comment]
@ddark008 Thanks! Yes, I will use this library. I've already started working on the integration.

**Comment by denisoed** [comment]
Progress

![image](https://user-images.githubusercontent.com/17797700/108628656-642c5a00-7486-11eb-8355-dcab8dc8eaa7.png)

**Comment by ddark008** [comment]
Look sexy)

**Comment by baptisteArno** [comment]
It looks awesome! Can't wait for this :)

**Comment by kevingzhang** [comment]
cannot wait for this feature.

**Comment by denisoed** [comment]
Sorry guys, I don't have time to finish this thing yet(((

**Comment by matiasvc** [comment]
I would also love this feature.

**Comment by Shriv3n** [comment]
+1 for this feature, it would be killer.

**Comment by ZinaL88** [comment]
This looks amazing! Is the feature stable?

**Comment by ungerik** [comment]
Seems that there is an official API now: https://developer.grammarly.com/

**Comment by denisoed** [comment]
@ungerik Thanks, but I still don't have time to do the integration Grammarly :(

**Comment by miharekar** [comment]
There is a VS Code extension, maybe you can reuse some of its code?

https://github.com/znck/grammarly/

**Comment by VidathD** [comment]
Any progress?

**Comment by denisoed** [comment]
@VidathD Hi

https://github.com/denisoed/obsidian-orthography/issues/9#issuecomment-1025972729

**Comment by VidathD** [comment]
> @VidathD Hi
> 
> [#9 (comment)](https://github.com/denisoed/obsidian-orthography/issues/9#issuecomment-1025972729)

Ah Ok. Sorry about that. My bad. I saw that but didn't pay much attention. Apologies. Keep up the good work mate...

**Comment by denisoed** [comment]
https://github.com/denisoed/obsidian-orthography/releases/tag/2.0.0
