### ISSUE TITLE
Can't select translation

### ISSUE THREAD

**Issue by MatteCrystal** [denisoed/obsidian-orthography#6]
I love and hate this plugin right now. Usually the spell check works and underlines the misspelled words and correctly shows the dropdown for possible spellings. The problem is often clicking on the correct spelling does nothing. That said there are other times it does work correctly. It seems like it just breaks randomly and IDK what exactly is causing it. 

I do run some custom css and plugins but turning them on and off as far as I can tell hasn't fixed the issue. That said If anything on my end is causing issue I would expect it to be other plugins or the version of obsidian I'm on.
![image](https://user-images.githubusercontent.com/32424764/109068032-eef29c00-76b4-11eb-8830-8fff616cbc11.png)

Are these issues present for others or is it just me? What plugins if any do you think might interfere with this plugin. 

I also had a thought that maybe it has something to do with the layout of windows and or linked windows. Is there any chance a weird mixture of windows could cause this issue. I generally have the following layout where all windows are on top of a backlinks window. the top leftmost is local graph and middle top is editing page, next is preview. All of them are linked. Then anything further to the right is unlinked pages but all are still on top of the backlinks panel.

![image](https://user-images.githubusercontent.com/32424764/109068955-2a419a80-76b6-11eb-9433-7ebbe27115ea.png)

**Comment by denisoed** [comment]
@MatteCrystal Thank you more for your feedback, I really appreciate it. :)
I have already started looking into this problem, hopefully I can get it fixed in the next few days.

**Comment by denisoed** [comment]
Please update plugin

https://github.com/denisoed/obsidian-orthography/releases/tag/2.0.0
