### ISSUE TITLE
Problem with selection clicking

### ISSUE THREAD

**Issue by chetachiezikeuzor** [denisoed/obsidian-orthography#7]
I quite like this plugin! When I first started using it, I really enjoyed being able to correct my (many) spelling mistakes in my notes. It's a much better option than Obsidian's Spell check. Though, in the last few weeks, the plugin just hasn't been working that well. Sometimes I'll turn it on, and when I click the selection, nothing happens. I do have a good amount of plugins installed, so this might be an issue on my end. If it helps, I've included a video of my console when I click to replace a word. Thanks!

https://user-images.githubusercontent.com/79069364/118377527-64bf2300-b593-11eb-9938-1d5f8394f466.mov

https://user-images.githubusercontent.com/79069364/118377702-79e88180-b594-11eb-9d3a-53c7fef755d2.mov

**Comment by denisoed** [comment]
Please update plugin

https://github.com/denisoed/obsidian-orthography/releases/tag/2.0.0
