### ISSUE TITLE
plugin does nothing

### ISSUE THREAD

**Issue by Aneeqasif** [denisoed/obsidian-orthography#9]
hi denisoed extremely sorry to say but this plugin is not working i have tried both by using stor and also building by source but i doesnt work the button just keep spining, 
looking forword for ur reponse

**Comment by denisoed** [comment]
Hi @Aneeqasif 
The first version of the plugin is no longer supported.
I started working on the second version of the plugin, so I will soon fix all the bugs.

Progress can be seen in this branch >  https://github.com/denisoed/obsidian-orthography/tree/develop

Thanks for the feedback!

**Comment by denisoed** [comment]
https://github.com/denisoed/obsidian-orthography/releases/tag/2.0.0
